/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_TradeApi_WRAP_H_
#define SWIG_TradeApi_WRAP_H_

#include <map>
#include <string>


class SwigDirector_TradeSpi : public TradeSpi, public Swig::Director {

public:
    SwigDirector_TradeSpi(PyObject *self);
    virtual void OnOrderReport(ITG::OrderInfo const *confirm);
    virtual void OnTradeReport(ITG::TradeInfo const *fill);
    virtual void OnQueryPosition(ITG::PositionInfo const *pos_info, std::string request_id, bool is_last);
    virtual void OnQueryAsset(ITG::AssetInfo const *asset_info, std::string request_id, bool is_last);
    virtual void OnQueryOrder(ITG::OrderInfo const *order_info, std::string request_id, bool is_last);
    virtual void OnQueryTrade(ITG::TradeInfo const *trade_info, std::string request_id, bool is_last);
    virtual void OnQuotData(ITG::QuotationData const *quot_data);
    virtual void OnQuotDeal(ITG::QuotationDeal const *quot_deal);
    virtual void OnQuotOrder(ITG::QuotationOrder const *quot_order);
    virtual void OnQuotStatic(ITG::StaticData const *static_data, std::string request_id, bool is_last);

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class TradeSpi doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[10];
#endif

};


#endif
